version: '3.8'

services:
  job-search-storage:
    container_name: job-search-storage
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_DB: job-search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d job-search -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  job-search-backend:
    container_name: job-search-backend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      quarkus.datasource.username: postgres
      quarkus.datasource.password: postgres
      quarkus.datasource.jdbc.url: jdbc:postgresql://job-search-storage:5432/job-search